name: auto_commit
description: A sample command-line application.
version: 1.0.4+33
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

executables:
  flit: auto_commit

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  args: ^2.6.0
  cli_spin: ^1.0.1
  http: ^1.2.2
  openai_dart: ^0.4.5
  package_info_plus: ^8.1.1
  process_run: ^1.2.2
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.1.0
  test: ^1.24.0
